version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
      
  pipeline:
    build: .
    container_name: pdf2latex_pipeline
    depends_on:
      - ollama
    volumes:
      - ./:/app
    environment:
      # Point the pipeline to the ollama container's host:port
      - OLLAMA_HOST=ollama:11434
      # Optionally hide GPUs in the pipeline container if you prefer CPU-only for model runs
      # - CUDA_VISIBLE_DEVICES=
    command: ["python", "pipeline.py"]

deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: 1 # alternatively, use `count: all` for all GPUs
          capabilities: [gpu]

networks:
  default:
    name: pdf2latex_net
